insert into student(id, firstname, lastname, email_address) values (11, 'Ali', 'Veli', 'ali.veli@gmail.com')
insert into student(id, firstname, lastname, email_address) values (12, 'Batu', 'Bay', 'batu.bay@gmail.com')
insert into student(id, firstname, lastname, email_address) values (13, 'Semih', 'Tek', 'semih.tek@gmail.com')
insert into student(id, firstname, lastname, email_address) values (14, 'Pinar', 'Veli', 'pinar.veli@gmail.com')
insert into student(id, firstname, lastname, email_address) values (15, 'Hasan', 'Veli', 'hasan.veli@gmail.com')